### ISSUE TITLE
secrets: forbidden

### ISSUE THREAD

**Issue by bangonkali** [Identitry/cert-manager-webhook-loopia#4]
# Summary

I am getting the following issue which maybe related to https://github.com/neoskop/cert-manager-webhook-dnsimple/issues/8#issuecomment-850351664.

I am quite sure secret `loopia-mydomain-issuer-credentials` exists on namespace `cert-manager`.

```
I1004 09:49:13.709848       1 dns.go:88] cert-manager/controller/challenges/Present "msg"="presenting DNS01 challenge for domain" "dnsName"="staging.mydomain.com" "domain"="staging.mydomain.com" "resource_kind"="Challenge" "resource_name"="staging-mydomain-com-nnw2b-1608050242-1242144700" "resource_namespace"="default" "resource_version"="v1" "type"="DNS-01"
E1004 09:49:13.969132       1 controller.go:163] cert-manager/controller/challenges "msg"="re-queuing item due to error processing" "error"="unable to get credential: failed to load secret \"cert-manager/loopia-mydomain-issuer-credentials\": secrets \"loopia-mydomain-issuer-credentials\" is forbidden: User \"system:serviceaccount:cert-manager:cert-manager-webhook-loopia\" cannot get resource \"secrets\" in API group \"\" in the namespace \"cert-manager\"" "key"="default/staging-mydomain-com-nnw2b-1608050242-1242144700"
```

```
$ kubectl get secret loopia-mydomain-issuer-credentials  --namespace=cert-manager
NAME                             TYPE     DATA   AGE
loopia-mydomain-issuer-credentials   Opaque   2      16m
```

# Version

```
k3s version v1.21.5+k3s1 (acad8ef8)
go version go1.16.8
```

**Comment by ExhaleSthlm** [comment]
Looks like the webhook is installed in the "default" namespace and resources in that namespace won't have access to resources in the "cert-manager" namespace without adding ClusterRole/Binding. I would recommend installing the webhook in the "cert-manager" namespace, in that case you don't need any extra config.

**Comment by tmansson** [comment]
I had the same issue while running against cert-manager 1.6.1. There might be a more efficient way, but after adding this RBAC it worked.

```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-webhook-loopia
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-webhook-loopia
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-loopia
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager
```
